# Generated by Django 4.1.7 on 2023-02-24 14:06

import apps.catalog.utils.uploading
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('slug', models.SlugField(help_text='Подсказка: введите название товара английскими буквами, заменяя пробелы нижними подчеркиваниями. Пример: kvadratniy_pouf', max_length=30, unique=True, verbose_name='Имя ссылки')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.catalog.utils.uploading.upload_function, verbose_name='Главное фото')),
                ('shirt_description', models.CharField(blank=True, default='', max_length=50, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('width', models.PositiveSmallIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Высота')),
                ('depth', models.PositiveSmallIntegerField(verbose_name='Глубина')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to=apps.catalog.utils.uploading.upload_function, verbose_name='Изображение')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
