version: "3"

services:
  db:
    image: postgres
#    command:
#      - "psql"
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
