# Generated by Django 3.2.6 on 2021-08-08 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pouf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('small_description', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(default='Без Категории', on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.category')),
            ],
        ),
    ]
