# Generated by Django 3.2.6 on 2021-08-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='pouf',
            options={'verbose_name': 'Пуф', 'verbose_name_plural': 'Пуфы'},
        ),
        migrations.AddField(
            model_name='pouf',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
