# Generated by Django 3.2.7 on 2021-10-04 11:30

import catalog.utils.uploading
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.utils.uploading.upload_function),
        ),
    ]
