# Generated by Django 3.2.6 on 2021-08-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210808_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pouf',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.category'),
        ),
    ]
