# Generated by Django 3.2.7 on 2021-10-05 08:10

import catalog.utils.uploading
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211004_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.utils.uploading.upload_function, verbose_name='Главное фото'),
        ),
    ]
