# Generated by Django 3.2.6 on 2021-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_pouf_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pouf',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='pouf',
            name='id',
        ),
        migrations.AddField(
            model_name='pouf',
            name='depth',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pouf',
            name='height',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pouf',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pouf',
            name='width',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pouf',
            name='number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
